### ISSUE TITLE
error: /bin/sh: 2: gcloud not found

### ISSUE THREAD

**Issue by chiokejjones** [terraform-google-modules/terraform-google-gcloud#10]
Hi all,

`Terraform v0.12.18`

The null_resource "run_command" is generating the follow error:

    module.non_prod.module.gcp_workspace_factory.module.gcloud.null_resource.run_command[0]: Destroying... [id=490511438395957534]
    module.non_prod.module.gcp_workspace_factory.module.gcloud.null_resource.run_command[0]: Provisioning with 'local-exec'...
    module.non_prod.module.gcp_workspace_factory.module.gcloud.null_resource.run_command[0] (local-exec): Executing: ["/bin/sh" "-c" "PATH=/terraform/non-prod/.terraform/modules/non_prod.gcp_workspace_factory.gcloud/terraform-google-modules-terraform-google-gcloud-b3cb8e9/cache/linux/google-cloud-sdk/bin:$PATH\ngcloud iam service-accounts enable projects/project-123456/serviceAccounts/project-service-account@project-123456.iam.gserviceaccount.com\n"]
    2019/12/26 17:19:52 [WARN] Errors while provisioning null_resource.run_command[0] with "local-exec", so aborting
    2019/12/26 17:19:52 [ERROR] module.non_prod.module.gcp_workspace_factory.module.gcloud: eval: *terraform.EvalApplyPost, err: 1 error occurred:
	    * Error running command 'PATH=/terraform/non-prod/.terraform/modules/non_prod.gcp_workspace_factory.gcloud/terraform-google-modules-terraform-google-gcloud-b3cb8e9/cache/linux/google-cloud-sdk/bin:$PATH
    gcloud iam service-accounts enable projects/project-123456/serviceAccounts/project-service-account@project-123456.iam.gserviceaccount.com
    ': exit status 127. Output: /bin/sh: 2: gcloud: not found

The module logic I'm using is below:

    module "gcloud" {
      source                            = "terraform-google-modules/gcloud/google"
      version                           = "~> 0.1"
      use_tf_google_credentials_env_var = "true"
  
      create_cmd_body  = "iam service-accounts disable ${module.project_factory.service_account_name}"
      destroy_cmd_body = "iam service-accounts enable ${module.project_factory.service_account_name}"
    }

**Comment by morgante** [comment]
What platform are you using? And can you run `terraform version`?

**Comment by milesmatthias** [comment]
@chiokejjones could you try explicitly setting the version for this module to `v0.2.0` and let us know if it was successful? There was a big change in `v0.3.0` that shifted things around quite a bit.

**Comment by chiokejjones** [comment]
Hey fellas.

@morgante I'm using Terraform Enterprise running `Terraform v0.12.18`.

@milesmatthias I receive the same error when explicitly setting `v0.2.0` or `v0.1.0`.

**Comment by morgante** [comment]
@chiokejjones How about with `v0.3.0`? @taylorludwig Could your changes have caused this? Maybe we can test on Terraform Cloud.

**Comment by taylorludwig** [comment]
@morgante the command looks good. I see the `PATH` updated as expected with the new `v0.3.0` changes. 

I did notice in the output above the command is `gcloud iam service-accounts enable projects/...` but **`enable`** is the `destroy_cmd_body` 

So it would make sense that it fails on `destroy` - the `decompress` and `upgrade` resources wouldn't have run on a fresh new vm/container (as terraform cloud would do) just to do a destroy so `gcloud` command wouldn't be there. 

I believe it would have failed prior to `v0.3.0` for the same reason. 

@chiokejjones could you confirm if its failing on `destroy` and not `apply`? 

I can setup a terraform cloud project to replicate

**Comment by taylorludwig** [comment]
I was able to replicate the same error on terraform cloud during a `destroy`. 

`apply` worked as intended. I'll see if I can find a way to force the provision steps to happen on `destroy` for the setup gcloud resources.

**Comment by chiokejjones** [comment]
@morgante I received the same error on all three versions.

@taylorludwig It seems to force the destroy of the `null_resources` regardless if I'm making a change to the service account or not.  I can try removing the `destroy_cmd_body` from the module logic.

**Comment by taylorludwig** [comment]
The way it is now just setting `destroy_cmd_body` to something like `""` would still break because it'll still attempt to just run `gcloud ` at destroy time before the executable is there. 

If you also set `destroy_cmd_entrypoint = ""` that should at least let terraform destroy finish. Obviously the iam-service-account would still be disabled for you since the `enable` on destroy wouldn't run.

**Comment by taylorludwig** [comment]
I was able to get create and destroy working with my PR here https://github.com/terraform-google-modules/terraform-google-gcloud/pull/11

@morgante seems a bit hacky and a lot of duplicate `null_resource` `local-exec` resources. But it does make sure that gcloud is decompressed and setup in the proper order during a destroy. 

Output of my terraform cloud runs
 
[apply.txt](https://github.com/terraform-google-modules/terraform-google-gcloud/files/4006510/apply.txt)

[destroy.txt](https://github.com/terraform-google-modules/terraform-google-gcloud/files/4006507/destroy.txt)

**Comment by chiokejjones** [comment]
> The way it is now just setting `destroy_cmd_body` to something like `""` would still break because it'll still attempt to just run `gcloud ` at destroy time before the executable is there.
> 
> If you also set `destroy_cmd_entrypoint = ""` that should at least let terraform destroy finish. Obviously the iam-service-account would still be disabled for you since the `enable` on destroy wouldn't run.

@taylorludwig Thanks for the suggestion.  Nulling those two parameters allowed the destroy to finish.
