### ISSUE TITLE
Get kubectl command stdout

### ISSUE THREAD

**Issue by fatehMohamed14** [terraform-google-modules/terraform-google-gcloud#102]
Is there a way to get the result of a command

For example getting the secrets 

       source = "terraform-google-modules/gcloud/google//modules/kubectl-wrapper"
       kubectl_create_command  = "kubectl get secrets"

how to get the result of this command

**Comment by morgante** [comment]
There's not currently a way to retrieve command outputs. What I recommend you do is pipe the output into a local file then retrieve it using the [local_file](https://registry.terraform.io/providers/hashicorp/local/latest/docs/data-sources/file) data source.

**Comment by bharathkkb** [comment]
@fatehMohamed14 you can use the K8s provider and [secrets data source](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/data-sources/secret) to retrieve it.
