### ISSUE TITLE
GOOGLE_CREDENTIALS should be accepted as either JSON or it's base64 encoding

### ISSUE THREAD

**Issue by briantopping** [terraform-google-modules/terraform-google-gcloud#103]
Prior to parsing `GOOGLE_CREDENTIALS` as JSON, an attempt should be made to do a base64 decode on the string and using it to decode if base64 does not return an error. This is helpful in CI/CD such as Gitlab that allows the credentials to be masked in logs if they [match a regex](https://gitlab.endpoints.taara-cicd-gitlab-core-b894.cloud.goog/help/ci/variables/index#mask-a-cicd-variable) that spots it.

**Comment by morgante** [comment]
Does Terraform itself support this? Our support for GOOGLE_CREDENTIALS is based on what the provider offers.

**Comment by briantopping** [comment]
Thanks for thinking this through. Is there a vector by which the `GOOGLE_CREDENTIALS` environment variable could simply be converted in place if they are base64?

**Comment by morgante** [comment]
What I would recommend doing is doing the conversion within your CI/CD pipeline.

**Comment by briantopping** [comment]
I can accept that.. thanks :)
