### ISSUE TITLE
Examples directory not reachable from the public docs page

### ISSUE THREAD

**Issue by kolban-google** [terraform-google-modules/terraform-google-gcloud#111]
### TL;DR

Visit this public page:

https://registry.terraform.io/modules/terraform-google-modules/gcloud/google/latest

Look in the usage section ... you will see a link to "examples".  Clicking here results in a 404 error.

### Expected behavior

Taken to a web page.

### Observed behavior

404 error

### Terraform Configuration

```hcl
Not applicable.
```

### Terraform Version

```sh
Not applicable.
```

**Comment by yuryninog** [comment]
Hi:
I have created a PR with a solution: https://github.com/terraform-google-modules/terraform-google-gcloud/pull/112

**Comment by morgante** [comment]
Technically this is an upstream issue: https://github.com/hashicorp/terraform/issues/21452
