### ISSUE TITLE
Add a support to use Workload Identity Config File to login

### ISSUE THREAD

**Issue by kakarot291994** [terraform-google-modules/terraform-google-gcloud#151]
### Add a support to use Workload Identity Config File to login

We are using gcloud moudle to run some gcloud command as we are enabling Workload Identity Federation to go key less which is recommended but it seems that module only support gcloud auth activate-service-account which in turn doesn't support the Workload Identify config credentials.

Due to this we are getting the following error while invoking gcloud: -

`Error: local-exec provisioner error
with module.wait_cfgmgmt_ns_core.null_resource.gcloud_auth_service_account_key_file[0],
on .terraform/modules/wait_cfgmgmt_ns_core/google-provided/gcloud/main.tf line 184, in resource "null_resource" "gcloud_auth_service_account_key_file":
184: provisioner "local-exec" {
Error running command 'gcloud auth activate-service-account --key-file
/__w/_temp/cred-config.json': exit status 1. Output:
ERROR: (gcloud.auth.activate-service-account) The .json key file is not in
a valid format`

**Comment by imranzunzani** [comment]
For those who stumble here, till this gets better (fixed), the alternative that works is using `--access-token-file` flag with the `gcloud` commands. 
To persist the access token:
```tf
data "google_client_config" "current" {
}

resource "local_sensitive_file" "auth_token" {
  filename = "${path.module}/auth_token.txt"
  content = data.google_client_config.current.access_token
}
```
Then supply the path of the file to the flag i.e. `--access-token-file=${path.module}/auth_token.txt`
