### ISSUE TITLE
BUG > Ephemeral container runs breaks decompress destroy hook

### ISSUE THREAD

**Issue by kuwas** [terraform-google-modules/terraform-google-gcloud#27]
# Description

Ephemeral container runs (like in Terraform Cloud or Enterprise) breaks decompress destroy hook. `null_resource.decompress_destroy` expects a tgz to be copied by `null_resource.copy`, but in a new container this cache does not exist and it does not get copied again during the destroy lifecycle hook.

This module seems to be designed with an existing vm runner (like Jenkins) in mind, which is contradictory to modern CI/CD platforms that encourage the use of ephemeral container builders. 

## Current Behavior

```
Error: Error running command 'tar -xzf .terraform/modules/project.project.project-factory.gcloud_delete/terraform-google-modules-terraform-google-gcloud-84e31b8/cache/0c610144/google-cloud-sdk.tar.gz
-C .terraform/modules/project.project.project-factory.gcloud_delete/terraform-google-modules-terraform-google-gcloud-84e31b8/cache/0c610144 &&
cp .terraform/modules/project.project.project-factory.gcloud_delete/terraform-google-modules-terraform-google-gcloud-84e31b8/cache/0c610144/jq
.terraform/modules/project.project.project-factory.gcloud_delete/terraform-google-modules-terraform-google-gcloud-84e31b8/cache/0c610144/google-cloud-sdk/bin/': exit status 2.
Output: tar (child): .terraform/modules/project.project.project-factory.gcloud_delete/terraform-google-modules-terraform-google-gcloud-84e31b8/cache/0c610144/google-cloud-sdk.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

## Expected Behavior

* `terraform destroy` should complete without any issues

## Steps to Reproduce

* Use a CI/CD platform that uses ephemeral containers
* In the first run, provision a project using this module
* In the second run, attempt to do a `terraform destroy`

## Additional Details

* Platform: Terraform Enterprise
* Terraform Version: `v0.12.20`
* Module Version: `~v0.5.0`

**Comment by grahamgilbert** [comment]
+1 on this. This is also impacting our deployments with TFE.

**Comment by travmcvey** [comment]
+1 here, I had to find a way to get around this error, or if you are trying to destroy a workspace. I hope this helps someone else..

(This work-around requires you to authenticate with TFE/TFCloud via `terraform login`)

I have found this to work pretty well (For TFE or TFCloud users) - It does involve updating the state, so please take caution:

1. Create a `backend.hcl`:

```terraform
workspaces { name = "your-workspace" }
hostname     = "app.terraform.io"
organization = "your-org"
```

2. Update your `provider.tf` (temporarily):

```terraform
terraform {

  backend "remote" {}
}
```

Then you need to run: `terraform init -backend-config=backend.hcl` NOTE: If you have a local terraform.tfstate file, it will ask if you want to convert the local state to the remote and overwrite what is there, ensure you respond with `NO`.(This is *very* important, please use care). 

You can then run: `terraform state list` If this still shows the same `null_*` resources that are failing in TFE/TFCloud run the following commands (As an example - from the project factory):

```bash
terraform state rm module.project-factory.module.gcloud_delete.null_resource.upgrade[0]
terraform state rm module.project-factory.module.gcloud_delete.null_resource.run_command[0]
terraform state rm module.project-factory.module.gcloud_delete.null_resource.prepare_cache[0]
terraform state rm module.project-factory.module.gcloud_delete.null_resource.gcloud_auth_google_credentials[0]
terraform state rm module.project-factory.module.gcloud_delete.null_resource.download_jq[0]
terraform state rm module.project-factory.module.gcloud_delete.null_resource.download_gcloud[0]
terraform state rm module.project-factory.module.gcloud_delete.null_resource.decompress[0]
```

**Comment by kuwas** [comment]
@travmcvey It is actually fine to always have the remote backend block in the terraform configuration, even if you're using a TFE/TFC workspace that is VCS-backed.

All of our repos have this, in order to facilitate local development with speculative plans.
