### ISSUE TITLE
Repo size is a few Gigs!

### ISSUE THREAD

**Issue by WillBeebe** [terraform-google-modules/terraform-google-gcloud#47]
Hi,

When cloning this repo I noticed it was _very_ large. Taking a look at the size of blobs..

```
git rev-list --objects --all \
| git cat-file --batch-check='%(objecttype) %(objectname) %(objectsize) %(rest)' \
| sed -n 's/^blob //p' \
| sort --numeric-sort --key=2 \
| cut -c 1-12,41- \
| $(command -v gnumfmt || echo numfmt) --field=2 --to=iec-i --suffix=B --padding=7 --round=nearest
```

I see that the largest blobs are:

```
d363c8a22ba7  844KiB cache/darwin/jq
f48b0ca92144  3.8MiB cache/linux/jq
75fd8ba99519   21MiB cache/darwin/google-cloud-sdk.tar.gz
8c9828a79cc1   21MiB cache/darwin/google-cloud-sdk.tar.gz
0de79388f3ff   22MiB cache/darwin/google-cloud-sdk.tar.gz
8e63c3b02a91   22MiB cache/darwin/google-cloud-sdk.tar.gz
a7e4b6be7829   22MiB cache/darwin/google-cloud-sdk.tar.gz
63002ef2c81d   22MiB cache/darwin/google-cloud-sdk.tar.gz
14171ecf8ace   22MiB cache/darwin/google-cloud-sdk.tar.gz
6afd38c96116   22MiB cache/darwin/google-cloud-sdk.tar.gz
b78769c44c12   22MiB cache/darwin/google-cloud-sdk.tar.gz
cc42739faf5f   28MiB cache/linux/google-cloud-sdk.tar.gz
c5f94c7cf7a2   28MiB cache/linux/google-cloud-sdk.tar.gz
8d0ac84483b2   29MiB cache/linux/google-cloud-sdk.tar.gz
6f3ced3b0c2d   29MiB cache/linux/google-cloud-sdk.tar.gz
2be0be2e1ead   29MiB cache/linux/google-cloud-sdk.tar.gz
3b288442db09   29MiB cache/linux/google-cloud-sdk.tar.gz
d9ae2e931b9e   29MiB cache/linux/google-cloud-sdk.tar.gz
113c1d621257   29MiB cache/linux/google-cloud-sdk.tar.gz
b042b74c3ce9   29MiB cache/linux/google-cloud-sdk.tar.gz
4a7bff9d634c   46MiB cache/darwin/google-cloud-sdk.tar.gz
d7d8e990a635   47MiB cache/darwin/google-cloud-sdk.tar.gz
cbed5f49838e   47MiB cache/darwin/google-cloud-sdk.tar.gz
9e243acd0dce   47MiB cache/darwin/google-cloud-sdk.tar.gz
ea809a943941   47MiB cache/darwin/google-cloud-sdk.tar.gz
d69e3b0586ee   47MiB cache/darwin/google-cloud-sdk.tar.gz
b3a6db909e8a   48MiB cache/darwin/google-cloud-sdk.tar.gz
8215801b7a25   48MiB cache/darwin/google-cloud-sdk.tar.gz
15c46155a4f6   48MiB cache/darwin/google-cloud-sdk.tar.gz
7679495ee5ec   49MiB cache/darwin/google-cloud-sdk.tar.gz
ef4529f27bab   53MiB cache/linux/google-cloud-sdk.tar.gz
16fb075994b2   54MiB cache/linux/google-cloud-sdk.tar.gz
3805942c637d   54MiB cache/linux/google-cloud-sdk.tar.gz
d7a7fe100c77   54MiB cache/linux/google-cloud-sdk.tar.gz
80d8c8e72df4   54MiB cache/linux/google-cloud-sdk.tar.gz
d4efd180bd7e   54MiB cache/linux/google-cloud-sdk.tar.gz
ca7c1d74d521   54MiB cache/linux/google-cloud-sdk.tar.gz
1cc4ef259c43   55MiB cache/linux/google-cloud-sdk.tar.gz
57edbbbbc87f   55MiB cache/linux/google-cloud-sdk.tar.gz
cb72bf30b7ef   56MiB cache/linux/google-cloud-sdk.tar.gz
```

In the gitignore I see that the cache directory is ignored. I'm assuming that was added after these were checked in.

It's pretty easy to remove large files from git history but something that's hard to express in a PR since you have to rewrite the git history. Anyway, I'd really appreciate if a repo owner could do this.

Thank you!

**Comment by bharathkkb** [comment]
Hi @WillBeebe  
That is right if you clone the repo, however should not be the case if you reference via the TF registry. We can some conversation here regarding this: https://github.com/terraform-google-modules/terraform-google-gcloud/issues/37#issuecomment-614499079
/cc @morgante

**Comment by WillBeebe** [comment]
No worries there. I was doing some bleeding edge dev and that's where it's impacting me. The initial clone is slow but not terrible, it's when my CI runs since there's not a released version of the module I'm using it clones down the repo. It's minor and really just code smell, happy either way here.

**Comment by mattford63** [comment]
We use Terragrunt to manage our estate and it does download the full repo each time :-(. Will any non-registry usage?

In our locked-down environments we basically build gcloud into a deploy container to solve any fetching issues.

For us to use this repo we've had to fork and use https://rtyley.github.io/bfg-repo-cleaner/ to strip out the big files.

And whilst it's great we can do this, it does feel like a unnatural coupling to have upstream.

**Comment by morgante** [comment]
I've cleaned up the history - should be much faster now!
