### ISSUE TITLE
Apply fails on mkdir if command has changed

### ISSUE THREAD

**Issue by jthn** [terraform-google-modules/terraform-google-gcloud#48]
The issue that I just ran into was that I changed the value of `create_cmd_body` after a successful apply, and could not run another apply. From what I can tell, this is probably due to the fact the `prepare_cache` null resource was invalidated (due to changing the value of arguments), but the random id was already in my state file, so it tried to create the same cache directory that I already had.

There are a few ways to fix this, the easiest would probably be just to change the command to `mkdir -p` [here](https://github.com/terraform-google-modules/terraform-google-gcloud/blob/master/main.tf#L38).

I suppose there are other things one could do, but most things that I can think of probably would result in unnecessary downloads of binaries, or would require terraform's `fileexists` to work with directories.

I solved this by deleting my local cache directory in `<root path>/.terraform/modules/<path to this module>/terraform-google-gcloud-x.x.x/cache/<random id>` in case anyone winds up running across this in the future.

Toss it on the pile I guess, because there's an easy workaround, and thanks for this module, really made my life a lot easier!

**Comment by morgante** [comment]
`mkdir -p` sounds like a good fix, happy to accept a PR.

**Comment by rohitworld90** [comment]
It simply fails to create any directory in my case. Running on Windows 10.

```
module.gcloud.null_resource.prepare_cache[0] (local-exec): Executing: ["cmd" "/C" "mkdir .terraform/modules/gcloud/terraform-google-gcloud-1.0.1/cache/334ca819"]
module.gcloud.null_resource.prepare_cache[0] (local-exec): The syntax of the command is incorrect.
```

It seems Windows mkdir can not create nested directories by default until something like this is done.

https://stackoverflow.com/questions/21224917/mkdir-in-windows-multiple-path-in-single-command/21225084

**Comment by jthn** [comment]
> `mkdir -p` sounds like a good fix, happy to accept a PR.

@morgante I see that #49 resolves this. Thanks!
