### ISSUE TITLE
 tar: Error opening archive: Failed to open '.terraform/modules/bootstrap.seed_project.project-factory.gcloud_disable

### ISSUE THREAD

**Issue by kemario** [terraform-google-modules/terraform-google-gcloud#64]
Having issue with executing this:

```
module.bootstrap.module.seed_project.module.project-factory.module.gcloud_disable.null_resource.copy[0]: Destroying... [id=4269937703596108229]
module.bootstrap.module.seed_project.module.project-factory.module.gcloud_disable.null_resource.copy[0]: Destruction complete after 0s
module.bootstrap.module.seed_project.module.project-factory.module.gcloud_disable.null_resource.copy[0]: Creating...
module.bootstrap.module.seed_project.module.project-factory.module.gcloud_disable.null_resource.copy[0]: Provisioning with 'local-exec'...
module.bootstrap.module.seed_project.module.project-factory.module.gcloud_disable.null_resource.copy[0] (local-exec): Executing: ["/bin/sh" "-c" "cp -R .terraform/modules/bootstrap.seed_project.project-factory.gcloud_disable/terraform-google-gcloud-0.5.1/cache/linux .terraform/modules/bootstrap.seed_project.project-factory.gcloud_disable/terraform-google-gcloud-0.5.1/cache/f4989ebd"]
module.bootstrap.module.seed_project.module.project-factory.module.gcloud_disable.null_resource.copy[0]: Creation complete after 0s [id=1751011585625952459]
module.bootstrap.module.seed_project.module.project-factory.module.gcloud_disable.null_resource.decompress[0]: Creating...
module.bootstrap.module.seed_project.module.project-factory.module.gcloud_disable.null_resource.decompress[0]: Provisioning with 'local-exec'...
module.bootstrap.module.seed_project.module.project-factory.module.gcloud_disable.null_resource.decompress[0] (local-exec): Executing: ["/bin/sh" "-c" "tar -xzf .terraform/modules/bootstrap.seed_project.project-factory.gcloud_disable/terraform-google-gcloud-0.5.1/cache/f4989ebd/google-cloud-sdk.tar.gz -C .terraform/modules/bootstrap.seed_project.project-factory.gcloud_disable/terraform-google-gcloud-0.5.1/cache/f4989ebd && cp .terraform/modules/bootstrap.seed_project.project-factory.gcloud_disable/terraform-google-gcloud-0.5.1/cache/f4989ebd/jq .terraform/modules/bootstrap.seed_project.project-factory.gcloud_disable/terraform-google-gcloud-0.5.1/cache/f4989ebd/google-cloud-sdk/bin/"]
module.bootstrap.module.seed_project.module.project-factory.module.gcloud_disable.null_resource.decompress[0] (local-exec): tar: Error opening archive: Failed to open '.terraform/modules/bootstrap.seed_project.project-factory.gcloud_disable/terraform-google-gcloud-0.5.1/cache/f4989ebd/google-cloud-sdk.tar.gz'


Error: Error running command 'tar -xzf .terraform/modules/bootstrap.seed_project.project-factory.gcloud_disable/terraform-google-gcloud-0.5.1/cache/f4989ebd/google-cloud-sdk.tar.gz -C .terraform/modules/bootstrap.seed_project.project-factory.gcloud_disable/terraform-google-gcloud-0.5.1/cache/f4989ebd && cp .terraform/modules/bootstrap.seed_project.project-factory.gcloud_disable/terraform-google-gcloud-0.5.1/cache/f4989ebd/jq .terraform/modules/bootstrap.seed_project.project-factory.gcloud_disable/terraform-google-gcloud-0.5.1/cache/f4989ebd/google-cloud-sdk/bin/': exit status 1. Output: tar: Error opening archive: Failed to open '.terraform/modules/bootstrap.seed_project.project-factory.gcloud_disable/terraform-google-gcloud-0.5.1/cache/f4989ebd/google-cloud-sdk.tar.gz'
```

When I check the directory 
```
ls -la .terraform/modules/bootstrap.seed_project.project-factory.gcloud_disable/terraform-google-gcloud-0.5.1/cache/420e8d8f/
total 16
drwxr-xr-x  4 blahuser  1533042234  128 Jul 23 10:54 .
drwxr-xr-x  6 blahuser  1533042234  192 Jul 23 10:54 ..
-rw-r--r--  1 blahuser  1533042234   40 Jul 23 10:54 google-cloud-sdk.tar.gz.REMOVED.git-id
-rw-r--r--  1 blahuser  1533042234   40 Jul 23 10:54 jq.REMOVED.git-id
```

Attempted removing the module and run terraform apply, get the same error message above.

```
terraform state rm ' module.bootstrap.module.seed_project.module.project-factory.module.gcloud_disable'
Removed module.bootstrap.module.seed_project.module.project-factory.module.gcloud_disable.null_resource.copy[0]
Removed module.bootstrap.module.seed_project.module.project-factory.module.gcloud_disable.null_resource.decompress[0]
Removed module.bootstrap.module.seed_project.module.project-factory.module.gcloud_disable.null_resource.decompress_destroy[0]
Removed module.bootstrap.module.seed_project.module.project-factory.module.gcloud_disable.null_resource.upgrade_destroy[0]
Removed module.bootstrap.module.seed_project.module.project-factory.module.gcloud_disable.random_id.cache
Successfully removed 5 resource instance(s).
```

**Comment by morgante** [comment]
After you've destroyed, what's the terraform plan show?

**Comment by kemario** [comment]
after I destroy it deletes resources. in order to get this to deploy i had to copy google-sdk files into the cache directory.

**Comment by morgante** [comment]
Ok, I'm confused though. If you removed the resources from the state, is it still raising an error?

**Comment by kemario** [comment]
If i remove the resources from the state file, the error still occurs.

**Comment by morgante** [comment]
Ok, please share your Terraform plan then (*after* you removed them from the state).

**Comment by bharathkkb** [comment]
@morgante could this have been due to the git rewrite?

**Comment by kemario** [comment]
Terraform plan
`module.bootstrap.random_id.suffix: Refreshing state... [id=HI4]
module.bootstrap.module.seed_project.module.project-factory.module.gcloud_deprivilege.random_id.cache: Refreshing state... [id=OPIYGg]
module.bootstrap.module.seed_project.module.project-factory.module.gcloud_delete.random_id.cache: Refreshing state... [id=-43nyA]
module.bootstrap.module.seed_project.module.project-factory.random_id.random_project_id_suffix: Refreshing state... [id=ERA]
module.bootstrap.module.seed_project.module.project-factory.module.gcloud_disable.random_id.cache: Refreshing state... [id=Qg6Njw]
module.bootstrap.google_organization_iam_member.org_billing_admin: Refreshing state... [id=345499518760/roles/billing.admin/group:gcp_billing@blahblah.com]
module.bootstrap.google_organization_iam_member.org_admin_serviceusage_consumer[0]: Refreshing state... [id=345499518760/roles/serviceusage.serviceUsageConsumer/group:it_operations@blahblah.com]
module.bootstrap.google_organization_iam_binding.billing_creator: Refreshing state... [id=345499518760/roles/billing.creator]
module.bootstrap.data.google_organization.org: Refreshing state...
module.bootstrap.google_organization_iam_member.tmp_project_creator: Refreshing state... [id=345499518760/roles/resourcemanager.projectCreator/group:it_operations@blahblah.com]
module.bootstrap.google_organization_iam_member.org_admins_group["roles/billing.user"]: Refreshing state... [id=345499518760/roles/billing.user/group:it_operations@blahblah.com]
module.bootstrap.google_organization_iam_member.org_admins_group["roles/resourcemanager.organizationAdmin"]: Refreshing state... [id=345499518760/roles/resourcemanager.organizationAdmin/group:it_operations@blahblah.com]
module.bootstrap.module.seed_project.module.project-factory.null_resource.preconditions: Refreshing state... [id=876400347694371852]
module.bootstrap.module.seed_project.module.project-factory.google_project.main: Refreshing state... [id=projects/blah-seed-1]
module.bootstrap.module.seed_project.module.project-factory.google_service_account.default_service_account: Refreshing state... [id=projects/blah-seed-1/serviceAccounts/project-service-account@blah-seed-1.iam.gserviceaccount.com]
module.bootstrap.module.seed_project.module.project-factory.module.project_services.google_project_service.project_services["serviceusage.googleapis.com"]: Refreshing state... [id=blah-seed-1/serviceusage.googleapis.com]
module.bootstrap.module.seed_project.module.project-factory.module.project_services.google_project_service.project_services["compute.googleapis.com"]: Refreshing state... [id=blah-seed-1/compute.googleapis.com]
module.bootstrap.module.seed_project.module.project-factory.module.project_services.google_project_service.project_services["iam.googleapis.com"]: Refreshing state... [id=blah-seed-1/iam.googleapis.com]
module.bootstrap.module.seed_project.module.project-factory.module.project_services.google_project_service.project_services["logging.googleapis.com"]: Refreshing state... [id=blah-seed-1/logging.googleapis.com]
module.bootstrap.module.seed_project.module.project-factory.data.null_data_source.default_service_account: Refreshing state...
module.bootstrap.module.seed_project.module.project-factory.module.project_services.google_project_service.project_services["servicenetworking.googleapis.com"]: Refreshing state... [id=blah-seed-1/servicenetworking.googleapis.com]
module.bootstrap.module.seed_project.module.project-factory.module.project_services.google_project_service.project_services["admin.googleapis.com"]: Refreshing state... [id=blah-seed-1/admin.googleapis.com]
module.bootstrap.module.seed_project.module.project-factory.module.project_services.google_project_service.project_services["cloudresourcemanager.googleapis.com"]: Refreshing state... [id=blah-seed-1/cloudresourcemanager.googleapis.com]
module.bootstrap.module.seed_project.module.project-factory.module.project_services.google_project_service.project_services["iamcredentials.googleapis.com"]: Refreshing state... [id=blah-seed-1/iamcredentials.googleapis.com]
module.bootstrap.module.seed_project.module.project-factory.module.project_services.google_project_service.project_services["appengine.googleapis.com"]: Refreshing state... [id=blah-seed-1/appengine.googleapis.com]
module.bootstrap.module.seed_project.module.project-factory.module.project_services.google_project_service.project_services["bigquery.googleapis.com"]: Refreshing state... [id=blah-seed-1/bigquery.googleapis.com]
module.bootstrap.module.seed_project.module.project-factory.module.project_services.google_project_service.project_services["cloudbilling.googleapis.com"]: Refreshing state... [id=blah-seed-1/cloudbilling.googleapis.com]
module.bootstrap.module.seed_project.module.project-factory.module.project_services.google_project_service.project_services["monitoring.googleapis.com"]: Refreshing state... [id=blah-seed-1/monitoring.googleapis.com]
module.bootstrap.module.seed_project.module.project-factory.module.project_services.google_project_service.project_services["storage-api.googleapis.com"]: Refreshing state... [id=blah-seed-1/storage-api.googleapis.com]
module.bootstrap.module.seed_project.module.project-factory.module.gcloud_disable.null_resource.copy[0]: Refreshing state... [id=7827771845948007246]
module.bootstrap.google_service_account.org_terraform: Refreshing state... [id=projects/blah-seed-1/serviceAccounts/org-terraform@blah-seed-1.iam.gserviceaccount.com]
module.bootstrap.google_storage_bucket.org_terraform_state: Refreshing state... [id=cft-tfstate-1c8e]
module.bootstrap.module.seed_project.module.project-factory.module.gcloud_disable.null_resource.decompress[0]: Refreshing state... [id=513014332531274501]
module.bootstrap.module.seed_project.module.project-factory.module.gcloud_disable.null_resource.upgrade[0]: Refreshing state... [id=5300642743817795343]
module.bootstrap.module.seed_project.module.project-factory.module.gcloud_disable.null_resource.run_command[0]: Refreshing state... [id=1204258869257390695]
module.bootstrap.module.seed_project.module.project-factory.module.gcloud_disable.null_resource.upgrade_destroy[0]: Refreshing state... [id=408926855098344919]
module.bootstrap.module.seed_project.module.project-factory.module.gcloud_disable.null_resource.decompress_destroy[0]: Refreshing state... [id=53406123856261929]
module.bootstrap.google_storage_bucket_iam_member.orgadmins_state_iam[0]: Refreshing state... [id=b/cft-tfstate-1c8e/roles/storage.admin/group:it_operations@blahblah.com]
module.bootstrap.google_storage_bucket_iam_member.org_terraform_state_iam: Refreshing state... [id=b/cft-tfstate-1c8e/roles/storage.admin/serviceaccount:org-terraform@blah-seed-1.iam.gserviceaccount.com]
module.bootstrap.google_organization_iam_member.tf_sa_org_perms["roles/orgpolicy.policyAdmin"]: Refreshing state... [id=345499518760/roles/orgpolicy.policyAdmin/serviceaccount:org-terraform@blah-seed-1.iam.gserviceaccount.com]
module.bootstrap.google_organization_iam_member.tf_sa_org_perms["roles/resourcemanager.organizationViewer"]: Refreshing state... [id=345499518760/roles/resourcemanager.organizationViewer/serviceaccount:org-terraform@blah-seed-1.iam.gserviceaccount.com]
module.bootstrap.google_organization_iam_member.tf_sa_org_perms["roles/compute.networkAdmin"]: Refreshing state... [id=345499518760/roles/compute.networkAdmin/serviceaccount:org-terraform@blah-seed-1.iam.gserviceaccount.com]
module.bootstrap.google_organization_iam_member.tf_sa_org_perms["roles/logging.configWriter"]: Refreshing state... [id=345499518760/roles/logging.configWriter/serviceaccount:org-terraform@blah-seed-1.iam.gserviceaccount.com]
module.bootstrap.google_organization_iam_member.tf_sa_org_perms["roles/resourcemanager.folderAdmin"]: Refreshing state... [id=345499518760/roles/resourcemanager.folderAdmin/serviceaccount:org-terraform@blah-seed-1.iam.gserviceaccount.com]
module.bootstrap.google_organization_iam_member.tf_sa_org_perms["roles/iam.serviceAccountTokenCreator"]: Refreshing state... [id=345499518760/roles/iam.serviceAccountTokenCreator/serviceaccount:org-terraform@blah-seed-1.iam.gserviceaccount.com]
module.bootstrap.google_organization_iam_member.tf_sa_org_perms["roles/iam.serviceAccountAdmin"]: Refreshing state... [id=345499518760/roles/iam.serviceAccountAdmin/serviceaccount:org-terraform@blah-seed-1.iam.gserviceaccount.com]
module.bootstrap.google_organization_iam_member.tf_sa_org_perms["roles/compute.xpnAdmin"]: Refreshing state... [id=345499518760/roles/compute.xpnAdmin/serviceaccount:org-terraform@blah-seed-1.iam.gserviceaccount.com]
module.bootstrap.google_organization_iam_member.tf_sa_org_perms["roles/serviceusage.serviceUsageConsumer"]: Refreshing state... [id=345499518760/roles/serviceusage.serviceUsageConsumer/serviceaccount:org-terraform@blah-seed-1.iam.gserviceaccount.com]
module.bootstrap.google_billing_account_iam_member.tf_billing_user[0]: Refreshing state... [id=014486-39DD00-FD9829/roles/billing.user/serviceaccount:org-terraform@blah-seed-1.iam.gserviceaccount.com]
module.bootstrap.google_service_account_iam_member.org_admin_sa_impersonate_permissions[0]: Refreshing state... [id=projects/blah-seed-1/serviceAccounts/org-terraform@blah-seed-1.iam.gserviceaccount.com/roles/iam.serviceAccountTokenCreator/group:it_operations@blahblah.com]
module.bootstrap.google_organization_iam_member.tf_sa_org_perms["roles/billing.user"]: Refreshing state... [id=345499518760/roles/billing.user/serviceaccount:org-terraform@blah-seed-1.iam.gserviceaccount.com]
module.bootstrap.google_organization_iam_member.tf_sa_org_perms["roles/iam.securityAdmin"]: Refreshing state... [id=345499518760/roles/iam.securityAdmin/serviceaccount:org-terraform@blah-seed-1.iam.gserviceaccount.com]
module.bootstrap.google_organization_iam_binding.project_creator: Refreshing state... [id=345499518760/roles/resourcemanager.projectCreator]`

**Comment by morgante** [comment]
Sorry, this looks like the raw refresh output. We need the plan - specifically the part which shows which resources are going to be changed/deleted. You can paste it in a gist.
