### ISSUE TITLE
Fix jq binary usage

### ISSUE THREAD

**Issue by tishen25** [terraform-google-modules/terraform-google-gcloud#67]
Users still need to install jq to use this module
https://github.com/terraform-google-modules/terraform-google-gcloud/blob/master/scripts/check_components.sh#L27

**Comment by morgante** [comment]
Actually, we should update the script so we don't need jq: https://github.com/terraform-google-modules/terraform-google-gcloud/blob/master/scripts/check_components.sh#L27

@bharathkkb Can you PTAL?

**Comment by bharathkkb** [comment]
Sounds good. This should be possible with gcloud native format/filters. I will try it out.
