### ISSUE TITLE
Path change during module upgrade results in error

### ISSUE THREAD

**Issue by bharathkkb** [terraform-google-modules/terraform-google-gcloud#75]
### Error
In a scenario as described below, upgrading from one module version to next results in error. 

```diff
module "foo" {
  source            = "terraform-google-modules/gcloud/google"
+  version           = "1.4.1"
-  version           = "1.4.0"
....
}
```

Error: 
```
 Error running command '.terraform/modules/bar.foo/terraform-google-gcloud-1.4.0/scripts/check_components.sh gcloud foo bar': exit status 127. Output: /bin/sh: .terraform/modules/bar.foo/terraform-google-gcloud-1.4.0/scripts/check_components.sh: not found
```

The reason seems to be that initially the directory structure is
```
main.tf
.terraform
    - modules > bar.foo > terraform-google-gcloud-1.4.0
```
but after a `tf init` with the new version of the module, it becomes
```
main.tf
.terraform
    - modules > bar.foo > terraform-google-gcloud-1.4.1
```
hence the file `.terraform/modules/bar.foo/terraform-google-gcloud-1.4.0/scripts/check_components.sh` no longer exists and has been replaced by `.terraform/modules/bar.foo/terraform-google-gcloud-1.4.1/scripts/check_components.sh`

### Workaround

Possible workaround seems to be to taint the resource but is not ideal.
```
terraform taint module.example.module.bar.foo.null_resource.additional_components_destroy[0]
```

**Comment by morgante** [comment]
Could we autotaint somehow? I don't see any easy fix here unfortunately.

**Comment by bharathkkb** [comment]
I believe this should longer be an issue as with https://github.com/hashicorp/terraform/issues/26143 the folder dir will no longer have the version appended. This should resolve the issue for most use cases, the only other case would be if we change the dir locations within the module. At that point, we should consider a breaking release or add some instructions to taint as defined here.
