### ISSUE TITLE
Running in Jenkins triggers recreation of run_command null_resource

### ISSUE THREAD

**Issue by thefirstofthe300** [terraform-google-modules/terraform-google-gcloud#81]
Because of the way that Jenkins and pathing works, the gcloud_bin_abs_path changes every Jenkins run and triggers unnecessary recreation of the `run_command` `null_resource`. Is including the absolute path necessary in the triggers?

**Comment by morgante** [comment]
Unfortunately Terraform requires everything referenced in null resources (including the command path) to be captured in triggers, so I don't think there's an easy fix here.

I'd recommend installing gcloud in Jenkins and disabling download completely: https://github.com/terraform-google-modules/terraform-google-gcloud#downloading

**Comment by rjouhann** [comment]
I have the same problem running Terraform gcloud module in Terraform Cloud. I don't think it is possible to install gcloud in Terraform cloud unfortunately.

Best would be to be able to ignore the `gcloud_bin_abs_path`. There is an existing issue open on Terraform to enable this generally for all module https://github.com/hashicorp/terraform/issues/27360.
