### ISSUE TITLE
This module does not detect drift in underlying kubernetes objects.

### ISSUE THREAD

**Issue by jaketf** [terraform-google-modules/terraform-google-gcloud#83]
### Problem Statement
I have an issue when using this module (indirectly from https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/tree/master/modules/workload-identity module) where it does not detect drift in the underlying kubernetes object and attempt to correct this drift.

### Use Case
Use Workload Identity module to annotate a KSA that is managed by a `helm_release`. This should handle the case where I taint the `helm_release` resource and re-apply (therefore destroying and recreating the KSA). I'd expect the workload identity module to detect the drift in the underlying resource which now has a KSA missing the annotation.

I've opened this against this module because I think more generally we should provide a way for this kubectl wrapper to detect drift in k8s objects.

### Ideas
I'm not a terraform expert but perhaps we could:
1. add some kind of "trigger" or "read" command, a kubectl command to run to determine if the create method should be run again.
1. expose some module level "recreate trigger" so I could tie this to my helm release resource saying "recreate this annotation every time the helm release modified".

cc my favorite terraform gymansts for hopefully more creative ideas: @brandonjbjelland  @morgante @bharathkkb

**Comment by bharathkkb** [comment]
> expose some module level "recreate trigger" 

Could we not use `create_cmd_triggers` for this?

**Comment by jaketf** [comment]
I think that'd be good. 
In my use case we could adapt WI module to use a trigger on KSA data source:
```hcl
  create_cmd_triggers = {
    ksa_metadata = join(",", [
      "data.kubernetes_service_account.example.uid",
      "data.kubernetes_service_account.example.generation",
  }
```
of course this would require configuring k8s provider.
