### ISSUE TITLE
Be able to specify path to gcloud for auth

### ISSUE THREAD

**Issue by rubyisbeautiful** [terraform-google-modules/terraform-google-gcloud#85]
Use `service_account_key_file` and `skip_download` together successfully.

Expected:
Be able to use these two options successfully when `gcloud` is not in the PATH

Result:
Fails when `gcloud` is not in PATH

Summary:
If the options `service_account_key_file` and `skip_download` are set, then [the command](https://github.com/terraform-google-modules/terraform-google-gcloud/blob/master/main.tf#L49) used has `local.gcloud` which value is simply `gcloud`.

Since there is no setting to specify either a global `gcloud` nor something like `authorize_cmd_entrypoint` this will fail if `gcloud` (the executable) is not in the path.

Request:
Either a global `gcloud_abs_path` input variable (the value of which would become, perhaps `local.gcloud_bin_path`, or a `authorize_cmd_entrypoint` variable to set the location of the gcloud used for auth.

**Comment by morgante** [comment]
Why do you need to keep `gcloud` outside the PATH?

**Comment by rubyisbeautiful** [comment]
Terraform is running on an executor VM, in a subprocess that we do not control.  gcloud is installed but not in the path.
We have workarounds, such as allowing the download in the module, but being able to specify the path to the gcloud install would be easy.  I can attempt a PR on this

**Comment by morgante** [comment]
Are you able to modify other environment variables?

For context, we're really trying to avoid introduce additional variables which must be plumbed through all wrapping modules. While conceptually I have no issue with adding a variable for specifying the path, I'm concerned that it would end up needing to be added to all modules which call this module as well. If possible, I'd prefer an approach closer to the (new) way we're handling downloading: https://github.com/terraform-google-modules/terraform-google-gcloud#downloading

**Comment by rubyisbeautiful** [comment]
I started [the change](https://github.com/rubyisbeautiful/terraform-google-gcloud/commit/cf94998b38d589908831dda17fd624630ce3be63); I see how it is wired to `kubectl-wrapper` and I guess you'd have to make `kubectl_wrapper.sh` a template since the `gcloud` is hardcoded in there.  Without 0.13+ module dependencies, you'd have to ensure the template is done before invoking that wrapper module.  Sounds feasible but a lot of changes.  I'll keep looking for workarounds.  Thanks for responding.
