### ISSUE TITLE
how quick is terraform updated if a new gcp feature is released?

### ISSUE THREAD

**Issue by hritz220** [terraform-google-modules/terraform-google-gcloud#88]
if the google cloud platform(GCP) is releasing a new feature, generally in how much time terraform update, to support that new GCP feature? Please let me know, it will be very helpful.

**Comment by morgante** [comment]
This module isn't the right place for that question: https://github.com/hashicorp/terraform-provider-google

Generally there is no official SLO for when Terraform support will be available. You can ask your Google account team to expedite features you need.
