### ISSUE TITLE
use_tf_google_credentials_env_var not chained in kubectl-wrapper

### ISSUE THREAD

**Issue by dansiviter** [terraform-google-modules/terraform-google-gcloud#93]
Version: 2.1.0

[kubectl-wrapper](/terraform-google-modules/terraform-google-gcloud/blob/v2.1.0/modules/kubectl-wrapper/main.tf) cannot make use of `use_tf_google_credentials_env_var` as it's not chained through. This means it can only authenticate using either a pre-authorised image or via a file path. Nether of which is possible via Terraform Cloud.

It is somewhat confusing that `use_tf_google_credentials_env_var` exists as I would have hoped it replicated the behaviour [described in the provider](https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#full-reference). However, that does not seem the case here and that would need a much bigger change so just chaining will suffice.

**Comment by bharathkkb** [comment]
fixed by https://github.com/terraform-google-modules/terraform-google-gcloud/pull/95
