### ISSUE TITLE
Module does not work with WIF creds

### ISSUE THREAD

**Issue by hitk6** [terraform-google-modules/terraform-google-gcloud#99]
Hello,

We are using WIF (Workload Identity Federation ) to deploy GKE cluster from AWS environment. I have successfully completed the following:

- Create a WIF for an AWS role.
- Initialize terraform gcp provider with WIF credentials.
- Terraform is running and creating various resources in GCP like vpc, subnet, cluster.

The problem I am facing is:

- In my terraform I am using module (https://github.com/terraform-google-modules/terraform-google-gcloud/tree/master/modules/kubectl-wrapper). This is failing with the following error. 

module.gke.module.gcloud_delete_default_kube_dns_configmap.module.gcloud_kubectl.null_resource.run_command[0] (local-exec): ERROR: (gcloud.container.clusters.get-credentials) Your current active account [email@mail.com] does not have any valid credentials.

Please guide me how to use WIF creds with this module.

Thank you

**Comment by morgante** [comment]
I don't have experience with Workload Identity Federation, but do you have an example of how you would be doing it on the command line (using `gcloud`) directly?

**Comment by angstwad** [comment]
This could occur if the `gcloud` is too old to support WIF.  Support for WIF was added in https://github.com/googleapis/google-auth-library-python/pull/698, and gcloud would need to pull it in.  I believe once gcloud is updated, it should just work.  I don't have WIF configured but I did just confirm that my install of gcloud (v 349.0.0) is using google-auth v 1.32.0.

**Comment by imranzunzani** [comment]
For those who stumble here, till this gets better (fixed), the approach that works with WIF is `--access-token-file` flag which I have explained [here](https://github.com/terraform-google-modules/terraform-google-gcloud/issues/151#issuecomment-2259254478). Hope it helps.
